# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: 'Delete Infra'
  displayName: 'Delete Infra'
  jobs: 
  - job: 'Delete'
    displayName: 'Delete job'
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Logan Enterprise Subscription'
        subscriptionId: '$(demoSubscriptionId)'
        action: 'DeleteRG'
        resourceGroupName: '$(demoResourceGroup)'